import { Link } from "react-router-dom";
import SEO from "../components/SEO";

export default function BhaskaraRao() {
  const expertise = ["Java and Spring Boot", "Microservices and distributed systems", "Payments and FinTech platforms", "Kafka and event-driven architecture", "Cloud, Docker and Kubernetes", "Reliability, observability and incident response", "AI-assisted engineering and RAG systems", "Engineering leadership and mentoring"];
  return <div className="min-h-screen bg-gradient-to-b from-black via-gray-900 to-gray-950 text-white">
    <SEO title="Bhaskara Rao Arani | Java, FinTech and Software Architect" description="Meet Bhaskara Rao Arani, CTO and software engineering leader specializing in Java, Spring Boot, payments, microservices, Kafka, cloud, observability, and AI systems." path="/about/bhaskara-rao" keywords="Bhaskara Rao Arani, Java architect, fintech architect, microservices expert Hyderabad" />
    <header className="pt-36 pb-20 border-b border-white/10"><div className="max-w-5xl mx-auto px-4"><p className="text-arin-orange uppercase tracking-widest font-semibold">Engineering Leadership</p><h1 className="text-5xl sm:text-6xl font-bold mt-4">Bhaskara Rao Arani</h1><p className="text-2xl text-gray-300 mt-4">CTO &amp; Co-Founder, ARIN IT Solutions</p><p className="text-lg text-gray-300 leading-relaxed mt-7 max-w-4xl">Bhaskara is a software engineering leader with more than 18 years of experience across enterprise Java, payments and FinTech, distributed systems, cloud platforms, production reliability, observability, technical delivery, mentoring, and architecture modernization.</p></div></header>
    <main className="max-w-5xl mx-auto px-4 py-20 space-y-16">
      <section><h2 className="text-3xl font-bold">Areas of Expertise</h2><div className="flex flex-wrap gap-3 mt-7">{expertise.map(item => <span key={item} className="px-4 py-2 rounded-full bg-white/10 border border-white/10">{item}</span>)}</div></section>
      <section className="grid md:grid-cols-2 gap-8"><article className="p-8 rounded-3xl bg-white/5 border border-white/10"><h2 className="text-2xl font-bold text-arin-orange">Architecture perspective</h2><p className="text-gray-300 mt-4 leading-relaxed">His approach begins with business capabilities, transaction integrity, data ownership, failure modes, operational control, and team boundaries. Technology decisions follow the context rather than precede it.</p></article><article className="p-8 rounded-3xl bg-white/5 border border-white/10"><h2 className="text-2xl font-bold text-arin-orange">Production perspective</h2><p className="text-gray-300 mt-4 leading-relaxed">Bhaskara treats logs, metrics, traces, recovery, capacity, security and delivery pipelines as part of application architecture. This is especially important for payment journeys and multi-service enterprise platforms.</p></article></section>
      <section><h2 className="text-3xl font-bold">Selected Engineering Work</h2><p className="text-gray-300 text-lg mt-5 leading-relaxed">His work includes payment-platform observability, high-priority incident triage, monitoring migrations, enterprise integration, Java microservices, event-driven systems, AI-native databases, contextual AI platforms, HR systems, logistics workflows, and developer mentoring.</p><div className="flex flex-wrap gap-5 mt-6"><Link to="/portfolio" className="text-arin-orange hover:underline">Explore case studies →</Link><Link to="/blog" className="text-arin-orange hover:underline">Read engineering articles →</Link><Link to="/contact" className="text-arin-orange hover:underline">Discuss an architecture challenge →</Link></div></section>
      <section><h2 className="text-3xl font-bold">Open-Source and Product Engineering</h2><p className="text-gray-300 text-lg mt-5 leading-relaxed">Bhaskara works on open-source and product initiatives including SochDB, an embedded AI-native database combining SQL, vectors and contextual memory; NullGuard, a Java stability-intelligence engine; and Nova, a layered emotional-intelligence architecture with memory, policy and safety controls.</p></section>
    </main>
  </div>;
}
