export const siteUrl = "https://arinits.com";

const page = (path, title, description, options = {}) => ({
  path,
  title,
  description,
  changefreq: "monthly",
  priority: "0.8",
  type: "website",
  ...options,
});

export const seoRoutes = [
  page("/", "Custom Software Development & IT Consulting | ARINITS", "Expert custom software development and strategic IT consulting. We deliver scalable enterprise software solutions. Start your digital transformation!", { changefreq: "weekly", priority: "1.0" }),
  page("/contact", "Contact Us - ARINITS", "Get in touch with ARINITS for custom software development, IT consulting, and enterprise technology solutions.", { priority: "0.9" }),
  page("/about", "About ARINITS | Software Engineering Hyderabad", "Learn how ARINITS approaches enterprise software, FinTech, AI, Java microservices, cloud, DevOps, and long-term technology partnerships.", { priority: "0.8" }),
  page("/about/bhaskara-rao", "Bhaskara Rao Arani | Java, FinTech and Software Architect", "Meet Bhaskara Rao Arani, CTO and software engineering leader specializing in Java, Spring Boot, payments, microservices, Kafka, cloud, observability, and AI systems.", { priority: "0.8", type: "profile" }),
  page("/portfolio", "Portfolio - ARINITS", "Explore ARINITS case studies in AI platforms, microservices, enterprise software, HR systems, and logistics.", { priority: "0.9" }),
  page("/team", "Our Team - ARINITS", "Meet the engineers and designers behind ARINITS and discover the expertise of our growing technology team."),
  page("/blog", "Software Engineering Blog - ARINITS", "Read practical insights on software development, cloud, DevOps, security, AI, architecture, and digital transformation.", { changefreq: "weekly" }),
  page("/blog/idempotent-payment-apis-prevent-duplicate-charges", "Idempotent Payment APIs: Prevent Duplicate Charges | ARINITS", "Design reliable payment APIs using idempotency keys, atomic writes, safe retries, Kafka deduplication, outbox events, recovery, and reconciliation.", { type: "article", priority: "0.8", publishedTime: "2026-09-16" }),
  page("/services/software-development", "Software Development Services - ARINITS", "Build scalable, secure enterprise applications tailored to your business with ARINITS custom software development services.", { priority: "0.9" }),
  page("/services/fintech-payment-solutions", "FinTech and Payment Software Development | ARINITS", "Engineer secure payment, wallet, reconciliation, merchant, case-management, and FinTech platforms with resilient APIs and auditable transaction workflows.", { priority: "0.9" }),
  page("/services/java-microservices", "Java Spring Boot Microservices Development | ARINITS", "Design and modernize scalable Java and Spring Boot platforms with domain-driven microservices, Kafka, security, observability, and Kubernetes.", { priority: "0.9" }),
  page("/services/ai-development", "AI Development Company in Hyderabad | ARINITS", "Build production-ready AI agents, RAG applications, enterprise copilots, and intelligent workflows with secure integration and measurable evaluation.", { priority: "0.9" }),
  page("/services/application-modernization", "Legacy Application Modernization Services | ARINITS", "Modernize legacy Java and enterprise applications through architecture assessment, modularization, APIs, cloud migration, DevOps, and observability.", { priority: "0.9" }),
  page("/industries/fintech", "FinTech Software Engineering Company | ARINITS", "Build resilient payment, banking, wallet, reconciliation, lending, and financial operations platforms with experienced FinTech engineers.", { priority: "0.9" }),
  page("/solutions/payment-reconciliation", "Payment Reconciliation Software Solutions | ARINITS", "Design automated payment reconciliation, settlement matching, exception management, audit trails, and operational reporting for FinTech platforms.", { priority: "0.9" }),
  page("/solutions/api-integration", "Enterprise API Integration Services | ARINITS", "Connect enterprise, payment, SaaS, and legacy platforms through secure APIs, events, webhooks, adapters, and observable integration workflows.", { priority: "0.9" }),
  page("/solutions/platform-engineering", "Platform Engineering Services | ARINITS", "Improve developer delivery with secure internal platforms, golden paths, CI/CD, Kubernetes, observability, and self-service infrastructure.", { priority: "0.9" }),
  page("/technologies/spring-boot", "Spring Boot Development and Consulting | ARINITS", "Build secure enterprise APIs and microservices with Java, Spring Boot, Spring Security, data access, testing, observability, and cloud deployment.", { priority: "0.8" }),
  page("/technologies/kafka", "Apache Kafka Consulting and Event-Driven Architecture | ARINITS", "Design reliable Kafka platforms with event contracts, partitioning, consumer groups, idempotency, retries, schema evolution, and observability.", { priority: "0.8" }),
  page("/technologies/kubernetes", "Kubernetes Consulting and Cloud-Native Platforms | ARINITS", "Run secure, observable and resilient applications on Kubernetes with workload design, autoscaling, deployment automation, policy, and recovery.", { priority: "0.8" }),
  page("/locations/software-development-company-hyderabad", "Software Development Company in Hyderabad | ARINITS", "Work with a Hyderabad software development company for enterprise applications, Java microservices, cloud platforms, web products, and modernization.", { priority: "0.9", areaServed: "Hyderabad, Telangana, India", serviceType: "Custom software development" }),
  page("/locations/fintech-development-company-india", "FinTech Development Company in India | ARINITS", "Build payment, reconciliation, wallet, merchant, banking integration, and financial operations software with an experienced FinTech development company in India.", { priority: "0.9", areaServed: "India", serviceType: "FinTech software development" }),
  page("/locations/java-consulting-services-hyderabad", "Java Consulting Services in Hyderabad | ARINITS", "Get Java consulting in Hyderabad for Spring Boot architecture, microservices, Kafka, performance, modernization, cloud deployment, and production reliability.", { priority: "0.9", areaServed: "Hyderabad, Telangana, India", serviceType: "Java consulting" }),
  page("/services/it-consulting", "Strategic IT Consulting Services | ARINITS", "Get strategic technology and architecture guidance that drives business growth and digital transformation.", { priority: "0.9" }),
  page("/services/web-development", "Custom Web Development Services | ARINITS", "We design and engineer responsive, high-performance websites and web applications that turn business ideas into reliable digital products.", { priority: "0.9" }),
  page("/services/app-development", "Mobile App Development Services | ARINITS", "Build secure, high-performance iOS and Android applications that deliver dependable user experiences.", { priority: "0.9" }),
  page("/services/technology-solutions", "Technology Solutions - ARINITS", "Modernize your business with cloud, DevOps, AI, automation, and enterprise technology solutions from ARINITS.", { priority: "0.9" }),
  page("/cloud-solutions", "Enterprise Cloud Solutions & Migration | ARINITS", "Accelerate digital transformation with enterprise cloud architecture, migration, modernization, and optimization services.", { priority: "0.9" }),
  page("/devops-services", "Expert DevOps Services & CI/CD Automation | ARINITS", "Accelerate software delivery with CI/CD automation, infrastructure as code, cloud-native platforms, and DevOps consulting.", { priority: "0.9" }),
  page("/cybersecurity-consulting", "Enterprise Cybersecurity Consulting Services | ARINITS", "Protect digital assets with cybersecurity consulting, security assessments, penetration testing, and zero-trust architecture.", { priority: "0.9" }),
  page("/terms", "Terms of Service - ARINITS", "Read the terms governing the ARINITS website, software development services, and technology consulting.", { changefreq: "yearly", priority: "0.3" }),
  page("/privacy", "Privacy Policy - ARINITS", "Learn how ARINITS collects, uses, and protects personal information.", { changefreq: "yearly", priority: "0.3" }),

  page("/blog/10-essential-tips-for-modern-web-development", "10 Essential Tips for Modern Web Development | ARINITS", "Discover best practices and techniques for building scalable, accessible, secure, and performant web applications.", { type: "article", priority: "0.7" }),
  page("/blog/cloud-migration-a-complete-guide", "Cloud Migration: A Complete Guide | ARINITS", "Learn how to migrate infrastructure to the cloud successfully, reduce costs, manage risk, and improve scalability.", { type: "article", priority: "0.7" }),
  page("/blog/building-secure-mobile-applications", "Building Secure Mobile Applications | ARINITS", "Explore mobile application security best practices covering authentication, encryption, API protection, and security testing.", { type: "article", priority: "0.7" }),
  page("/blog/the-future-of-ai-in-software-development", "The Future of AI in Software Development | ARINITS", "Learn how artificial intelligence is transforming software delivery, testing, debugging, code review, and developer productivity.", { type: "article", priority: "0.7" }),
  page("/blog/design-systems-building-consistent-uis", "Design Systems: Building Consistent UIs | ARINITS", "Learn how reusable components, design tokens, accessibility standards, and documentation create consistent product experiences.", { type: "article", priority: "0.7" }),
  page("/blog/devops-best-practices-for-modern-teams", "DevOps Best Practices for Modern Teams | ARINITS", "Improve delivery with CI/CD, infrastructure as code, containers, observability, and integrated security practices.", { type: "article", priority: "0.7" }),
  page("/blog/how-devops-reduces-deployment-time", "How DevOps Reduces Deployment Time | ARINITS", "Discover how DevOps practices, CI/CD automation, infrastructure as code, and microservices reduce enterprise deployment time.", { type: "article", priority: "0.7" }),
  page("/blog/cloud-security-best-practices-for-enterprises", "Cloud Security Best Practices for Enterprises | ARINITS", "Learn enterprise cloud security practices for zero-trust architecture, compliance, data protection, and proactive threat detection.", { type: "article", priority: "0.7" }),

  page("/portfolio/sochdb-ai-native-vector-sql-database", "SochDB AI-Native Vector and SQL Database | ARINITS", "See how ARINITS engineered SochDB, an AI-native database combining SQL, vector search, real-time ingestion, and agent memory.", { priority: "0.8" }),
  page("/portfolio/nova-ai-emotional-intelligence-platform", "Nova AI Emotional Intelligence Platform | ARINITS", "Explore Nova, a layered emotional-intelligence architecture with contextual memory, policy enforcement, and AI safety guardrails.", { priority: "0.8" }),
  page("/portfolio/enterprise-microservices-platform", "Enterprise Microservices Platform Case Study | ARINITS", "Explore a secure, containerized microservices platform using Spring Boot, API Gateway, JWT, Docker, and React.", { priority: "0.8" }),
  page("/portfolio/hrms-microservice-architecture", "HRMS Microservice Architecture Case Study | ARINITS", "See how ARINITS designed a modular HRMS platform with domain isolation, onboarding, recruitment, and role-based access.", { priority: "0.8" }),
  page("/portfolio/unified-order-delivery-tracking-platform", "Unified Order and Delivery Tracking Platform | ARINITS", "Explore a unified logistics platform with multi-channel integration, route optimization, event-driven tracking, and payments.", { priority: "0.8" }),
];
